FROM golang:1.20-alpine AS build

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o project .

FROM alpine

COPY --from=build /build/project /bin/project

ENTRYPOINT ["/bin/project"]

